language: php

php:
  - "5.6"
  - "5.5"
  - "5.4"
  - "hhvm"
  - "nightly"

branches:
  only:
    - master
    - develop
    - /^release\/.*$/

install:
  - composer install

script:
  - php test.php

matrix:
  allow_failures:
    - php: "nightly"

notifications:
  email:
    on_success: never
    on_failure: always

