language: php

php:
  - "5.6"
  - "5.5"
  - "5.4"
  - "5.3"
  - "hhvm"
  - "nightly"

branches:
  only:
    - master
    - develop
    - /^release\/.*$/

install:
  - composer install

script:
  - php test.php

matrix:
  allow_failures:
    - php: "5.3"
    - php: "nightly"

